# SponsorGen Configuration

# Output settings
outputDir: "./output"
cacheDir: "./cache"
refreshMinutes: 60
defaultAvatar: "./assets/default_avatar.svg"

# GitHub sponsor settings (optional)
githubToken: ""
githubLogin: ""
includePrivate: false
githubOrgs: []
excludeSponsors: []
includeSponsors: []
forceSponsorAmounts: {}

# OpenCollective settings (optional)
openCollectiveSlug: ""
openCollectiveKey: ""

# Patreon settings (optional)
patreonToken: ""
patreonCampaignId: ""

# Afdian settings (optional)
afdianUserId: ""
afdianToken: ""

# Rendering settings
avatarSize: 45
avatarMargin: 5
svgWidth: 800
fontSize: 14
fontFamily: "system-ui, -apple-system, 'Segoe UI', Roboto, Ubuntu, Cantarell, 'Noto Sans', sans-serif"
showAmount: false
showName: false
backgroundColor: "transparent"
paddingX: 10
paddingY: 10